name: Convert all markdown to pdfs

on: workflow_dispatch

permissions: 
  contents: write

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: convert md to pdf
        uses: docker://pandoc/latex:3.1
        with:
          entrypoint: /bin/sh
          args: -c 'tmp="${0}"; tmpb="output/${0%.md}.html"; mkdir output; find ./ -iname "*.md" -type f -exec sh -c \'pandoc ${tmp} --from markdown+tex_math_dollars --to html5 --standalone --highlight-style=breezeDark --mathjax -o ${tmpb}\' {} \;'
      - run: |
          git config user.name "convert-action"
          git config user.email "<>"
          git add .
          git commit -m "converted md to pdf"
          git push
