name: Deploy site with markdown as pdfs

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  convert_via_pandoc:
    name: Markdown to pdf via pandoc
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:3.1.1
        with:
          args: "--from markdown --to html5 --standalone --highlight-style=breezeDark --mathml *.md"
