name: Deploy site with markdown as pdfs

on: workflow_dispatch

permissions:
  contents: write

jobs:
  convert_via_pandoc:
    name: Markdown to pdf via pandoc
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:3.1.1
        with:
          run: find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} --from markdown --to html5 --standalone --highlight-style=breezeDark --mathml -o ${0%}.html' {} \;
      - run: |
          git config user.name 'pdf-convert-action'
          git config user.email '<>'
          git add .
          git commit -m "converted files"
          git push
