name: Convert all markdown to pdfs

on: workflow_dispatch

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - run: git --version
      - name: prepare output directory
        run: mkdir output
      - name: convert md to pdf
        run: |
          find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/${0%.md}.html' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
