name: Deploy site with markdown as pdfs

on: workflow_dispatch

permissions:
  contents: write

jobs:
  convert_via_pandoc:
    name: Markdown to pdf via pandoc
    runs-on: ubuntu-22.04
    container:
      image: docker://pandoc/latex:3.1.1
    steps:
      - uses: actions/checkout@v4
      - run: find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} --from markdown --to html5 --standalone --highlight-style=breezeDark --mathml -o ${0%}.html' {} \;
      - run: |
          git config --global user.name 'pdf-convert-action'
          git config --global user.email 'pdf-convert-action@users.noreply.github.com'
          git commit -am "converted files"
          git push
