name: Deploy site with markdown as pdfs

on: workflow_dispatch

permissions:
  contents: write

jobs:
  convert_via_pandoc:
    name: Markdown to pdf via pandoc
    runs-on: ubuntu-22.04
    container: 
      image: docker://pandoc/latex:3.1.1 
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir github
          cd github
          mkdir workspace
          cd ..
          find ./ -iname '*.md' -type f -exec sh -c "tmp=${0#./}; pandoc ${tmp} --from markdown --to html5 --standalone --highlight-style=breezeDark --mathml -o github/workspace/${tmp%.md}.html" {} \;
          ls
          git config user.name 'pdf-convert-action'
          git config user.email '<>'
          git add .
          git commit -m "converted files"
          git push
